/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.gui.options.panel;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import org.exbin.framework.gui.utils.LanguageUtils;
import org.exbin.framework.gui.utils.WindowUtils;
import org.exbin.framework.gui.options.api.OptionsCapable;
import org.exbin.framework.gui.options.api.OptionsModifiedListener;
import org.exbin.framework.gui.options.options.impl.AppearanceOptionsImpl;
import org.exbin.framework.gui.utils.ComponentResourceProvider;

/**
 * Toolbar appearance options panel.
 *
 * @version 0.2.1 2019/07/21
 * @author ExBin Project (http://exbin.org)
 */
@ParametersAreNonnullByDefault
public class AppearanceOptionsPanel extends javax.swing.JPanel implements OptionsCapable<AppearanceOptionsImpl>, ComponentResourceProvider {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(AppearanceOptionsPanel.class);
    private OptionsModifiedListener optionsModifiedListener;
    private OptionsCapable extendedPanel = null;

    public AppearanceOptionsPanel() {
        initComponents();
    }

    @Nonnull
    @Override
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    @Override
    public void loadFromOptions(AppearanceOptionsImpl options) {
        showToolbarCheckBox.setSelected(options.isShowToolBar());
        showCaptionsCheckBox.setSelected(options.isShowToolBarCaptions());
        showStatusbarCheckBox.setSelected(options.isShowStatusBar());
    }

    @Override
    public void saveToOptions(AppearanceOptionsImpl options) {
        options.setShowToolBar(showToolbarCheckBox.isSelected());
        options.setShowToolBarCaptions(showCaptionsCheckBox.isSelected());
        options.setShowStatusBar(showStatusbarCheckBox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarsOptionsPanel = new javax.swing.JPanel();
        showToolbarCheckBox = new javax.swing.JCheckBox();
        showCaptionsCheckBox = new javax.swing.JCheckBox();
        showStatusbarCheckBox = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        showToolbarCheckBox.setSelected(true);
        showToolbarCheckBox.setText(resourceBundle.getString("showToolbarCheckBox.text")); // NOI18N
        showToolbarCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showToolbarCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        showCaptionsCheckBox.setSelected(true);
        showCaptionsCheckBox.setText(resourceBundle.getString("showCaptionsCheckBox.text")); // NOI18N
        showCaptionsCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showCaptionsCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        showStatusbarCheckBox.setSelected(true);
        showStatusbarCheckBox.setText(resourceBundle.getString("showStatusbarCheckBox.text")); // NOI18N
        showStatusbarCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showStatusbarCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout toolBarsOptionsPanelLayout = new javax.swing.GroupLayout(toolBarsOptionsPanel);
        toolBarsOptionsPanel.setLayout(toolBarsOptionsPanelLayout);
        toolBarsOptionsPanelLayout.setHorizontalGroup(
            toolBarsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolBarsOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolBarsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCaptionsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(showStatusbarCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showToolbarCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        toolBarsOptionsPanelLayout.setVerticalGroup(
            toolBarsOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarsOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showToolbarCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCaptionsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showStatusbarCheckBox))
        );

        add(toolBarsOptionsPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void showToolbarCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showToolbarCheckBoxjCheckBoxItemStateChanged
        setModified(true);
    }//GEN-LAST:event_showToolbarCheckBoxjCheckBoxItemStateChanged

    private void showCaptionsCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showCaptionsCheckBoxjCheckBoxItemStateChanged
        setModified(true);
    }//GEN-LAST:event_showCaptionsCheckBoxjCheckBoxItemStateChanged

    private void showStatusbarCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showStatusbarCheckBoxjCheckBoxItemStateChanged
        setModified(true);
    }//GEN-LAST:event_showStatusbarCheckBoxjCheckBoxItemStateChanged

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new AppearanceOptionsPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox showCaptionsCheckBox;
    private javax.swing.JCheckBox showStatusbarCheckBox;
    private javax.swing.JCheckBox showToolbarCheckBox;
    private javax.swing.JPanel toolBarsOptionsPanel;
    // End of variables declaration//GEN-END:variables

    private void setModified(boolean modified) {
        if (optionsModifiedListener != null) {
            optionsModifiedListener.wasModified();
        }
    }

    @Override
    public void setOptionsModifiedListener(OptionsModifiedListener listener) {
        optionsModifiedListener = listener;
    }

    public void addExtendedPanel(OptionsCapable<?> optionsPanel) {
        if (extendedPanel != null) {
            remove((Component) extendedPanel);
        }
        extendedPanel = optionsPanel;
        add((Component) extendedPanel, BorderLayout.CENTER);
        extendedPanel.setOptionsModifiedListener(optionsModifiedListener);
    }
}
