/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.addon.manager.gui;

import java.awt.BorderLayout;
import java.util.Optional;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JButton;
import org.exbin.framework.App;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.framework.utils.OkCancelListener;
import org.exbin.framework.utils.UiUtils;
import org.exbin.framework.window.api.handler.CloseControlHandler;
import org.exbin.framework.window.api.handler.CloseControlHandler.CloseControlEnablementListener;

/**
 * Control panel for addons manager.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class AddonsControlPanel extends javax.swing.JPanel implements CloseControlHandler.CloseControlService {

    private final java.util.ResourceBundle resourceBundle;
    private CloseControlHandler handler;
    private Controller controller;
    private OkCancelListener okCancelListener;

    public AddonsControlPanel() {
        this(App.getModule(LanguageModuleApi.class).getBundle(AddonsControlPanel.class));
    }

    public AddonsControlPanel(java.util.ResourceBundle resourceBundle) {
        this.resourceBundle = resourceBundle;
        initComponents();

        okCancelListener = new OkCancelListener() {
            @Override
            public void okEvent() {
                performCloseClick();
            }

            @Override
            public void cancelEvent() {
                performCloseClick();
            }
        };
    }

    public void showLegacyWarning() {
        add(warningPanel, BorderLayout.CENTER);
    }

    public void setOperationState(OperationVariant variant, int selected) {
        switch (variant) {
            case INSTALL:
                operationButton.setText(resourceBundle.getString("installButton.text"));
                if (selected > 0) {
                    operationLabel.setText(String.format(resourceBundle.getString("installLabel.text"), selected));
                    operationButton.setEnabled(true);
                } else {
                    operationLabel.setText(null);
                    operationButton.setEnabled(false);
                }
                break;
            case UPDATE:
                operationButton.setText(resourceBundle.getString("updateButton.text"));
                if (selected > 0) {
                    operationLabel.setText(String.format(resourceBundle.getString("updateLabel.text"), selected));
                    operationButton.setEnabled(true);
                } else {
                    operationLabel.setText(null);
                    operationButton.setEnabled(false);
                }
                break;
            case UPDATE_ALL:
                operationButton.setText(resourceBundle.getString("updateAllButton.text"));
                operationButton.setEnabled(selected > 0);
                operationLabel.setText(null);
                break;
            default:
                throw new AssertionError();
        }
    }

    public void setHandler(CloseControlHandler handler) {
        this.handler = handler;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningPanel = new javax.swing.JPanel();
        warningLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        operationButton = new javax.swing.JButton();
        operationLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        warningPanel.setBackground(new java.awt.Color(255, 153, 0));

        warningLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(0, 0, 0));
        warningLabel.setText(resourceBundle.getString("warningLabel.text")); // NOI18N

        javax.swing.GroupLayout warningPanelLayout = new javax.swing.GroupLayout(warningPanel);
        warningPanel.setLayout(warningPanelLayout);
        warningPanelLayout.setHorizontalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        warningPanelLayout.setVerticalGroup(
            warningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());

        operationButton.setText(resourceBundle.getString("operationButton.text")); // NOI18N
        operationButton.setEnabled(false);
        operationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationButtonActionPerformed(evt);
            }
        });

        closeButton.setText(resourceBundle.getString("closeButton.text")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(operationButton)
                    .addComponent(operationLabel))
                .addContainerGap())
        );

        add(buttonsPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        if (handler != null) {
            handler.controlActionPerformed();
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void operationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationButtonActionPerformed
        if (controller != null) {
            controller.performOperation();
        }
    }//GEN-LAST:event_operationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton operationButton;
    private javax.swing.JLabel operationLabel;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JPanel warningPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void performCloseClick() {
        UiUtils.doButtonClick(closeButton);
    }

    @Nonnull
    @Override
    public Optional<JButton> getDefaultButton() {
        return Optional.of(closeButton);
    }

    @Nonnull
    @Override
    public OkCancelListener getOkCancelListener() {
        return okCancelListener;
    }

    @Nonnull
    @Override
    public CloseControlEnablementListener createEnablementListener() {
        return (boolean enablement) -> {
            closeButton.setEnabled(enablement);
        };
    }

    public interface Controller {

        void performOperation();
    }

    public enum OperationVariant {
        INSTALL,
        UPDATE,
        UPDATE_ALL
    }
}
