/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.addon.manager.gui;

import java.awt.Component;
import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import org.exbin.framework.App;
import org.exbin.framework.addon.manager.model.FilterListModel;
import org.exbin.framework.addon.manager.api.ItemRecord;
import org.exbin.framework.language.api.LanguageModuleApi;

/**
 * Panel for list of packs / addon suites.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class FilterListPanel extends javax.swing.JPanel {

    private final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(FilterListPanel.class);
    private Controller controller;
    private final FilterListModel filterListModel = new FilterListModel();

    public FilterListPanel() {
        initComponents();
        init();
    }

    private void init() {
        itemsList.setCellRenderer(new DefaultListCellRenderer() {

            private final AddonItemPanel addonItemPanel = new AddonItemPanel();

            @Nonnull
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                ItemRecord record = (ItemRecord) value;
                addonItemPanel.setItemRecord(list, record, isSelected, cellHasFocus);
                return addonItemPanel;
            }
        });
        itemsList.addListSelectionListener((event) -> {
            if (controller != null) {
                int index = itemsList.getSelectedIndex();
                if (index >= 0) {
                    controller.notifyItemSelected(itemsList.getModel().getElementAt(index));
                } else {
                    controller.notifyItemSelected(null);
                }
            }
        });
        Document document = filterTextField.getDocument();
        document.addDocumentListener(new DocumentListener() {

            private final Runnable filterFinished = () -> {
                filterListModel.notifyItemsChanged();
            };
            private String lastFilter = "";

            @Override
            public void insertUpdate(DocumentEvent de) {
                filterValueChanged();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                filterValueChanged();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                filterValueChanged();
            }

            public void filterValueChanged() {
                if (controller != null) {
                    String newFilter = filterTextField.getText();
                    if (!lastFilter.equals(newFilter)) {
                        lastFilter = newFilter;
                        controller.setFilter(newFilter, filterFinished);
                    }
                }
            }
        });
        itemsList.setModel(filterListModel);
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public void setRecordProvider(FilterListModel.RecordsProvider recordsProvider) {
        filterListModel.setProvider(recordsProvider);
    }

    public void notifyItemsChanged() {
        filterListModel.notifyItemsChanged();
        itemsList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterLabel = new javax.swing.JLabel();
        filterTextField = new javax.swing.JTextField();
        itemsListScrollPane = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList<>();

        filterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exbin/framework/addon/manager/resources/icons/open_icon_library/icons/png/22x22/view-filter.png"))); // NOI18N

        itemsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemsListScrollPane.setViewportView(itemsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemsListScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filterTextField)
                    .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsListScrollPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filterLabel;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JList<org.exbin.framework.addon.manager.api.ItemRecord> itemsList;
    private javax.swing.JScrollPane itemsListScrollPane;
    // End of variables declaration//GEN-END:variables

    @ParametersAreNonnullByDefault
    public interface Controller {

        void setFilter(String filter, Runnable finished);

        void notifyItemSelected(@Nullable ItemRecord itemRecord);
    }
}
