editUndoAction.text=Undo
editUndoAction.smallIcon=/org/exbin/jaguif/operation/undo/resources/icons/16px/edit-undo.png
editUndoAction.icon=/org/exbin/jaguif/operation/undo/resources/icons/22px/edit-undo.png
editUndoAction.shortDescription=Reverts last performed modification
editUndoAction.accelerator=ctrl pressed Z
editRedoAction.text=Redo
editRedoAction.smallIcon=/org/exbin/jaguif/operation/undo/resources/icons/16px/edit-redo.png
editRedoAction.icon=/org/exbin/jaguif/operation/undo/resources/icons/22px/edit-redo.png
editRedoAction.shortDescription=Restores last reverted operation
editRedoAction.accelerator=shift ctrl pressed Z
