/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.gui.service.catalog.panel;

import java.awt.Component;
import java.util.ResourceBundle;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.gui.utils.LanguageUtils;
import org.exbin.framework.gui.utils.WindowUtils;
import org.exbin.xbup.core.catalog.XBACatalog;
import org.exbin.xbup.core.catalog.base.XBCItem;
import org.exbin.xbup.core.catalog.base.XBCRev;
import org.exbin.xbup.core.catalog.base.XBCSpec;
import org.exbin.xbup.core.catalog.base.service.XBCRevService;

/**
 * XBManager catalog specification's revision selection panel.
 *
 * @version 0.2.1 2019/06/27
 * @author ExBin Project (http://exbin.org)
 */
public class CatalogSelectRevPanel extends javax.swing.JPanel {

    private XBApplication application;
    private XBCRevService revService;
    private final CatalogItemsSearchPanel selectSpecPanel;
    private final CatalogRevsComboBoxModel revsModel;
    private boolean selectEnabled;
    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(CatalogSelectRevPanel.class);

    public CatalogSelectRevPanel(XBACatalog catalog, CatalogSpecItemType specType) {
        revsModel = new CatalogRevsComboBoxModel();
        selectSpecPanel = new CatalogItemsSearchPanel();
        selectSpecPanel.setApplication(application);
        selectSpecPanel.setCatalog(catalog);
        initComponents();

        if (catalog != null) {
            revService = (XBCRevService) catalog.getCatalogService(XBCRevService.class);
        }

        init();
        selectSpecPanel.switchToSpecTypeMode(specType);
    }

    private void init() {
        add(selectSpecPanel);
        selectSpecPanel.setSelectionListener((XBCItem spec) -> {
            selectEnabled = spec != null;
            if (spec != null) {
                if (spec instanceof XBCSpec) {
                    revsModel.setRevs(revService.getRevs((XBCSpec) spec));
                    targetRevisionComboBox.setSelectedIndex(revsModel.getSize() - 1);
                } else {
                    revsModel.getRevs().clear();
                }
            } else {
                targetRevisionComboBox.setSelectedIndex(-1);
                revsModel.getRevs().clear();
            }

            revsModel.fireDataChanged();
        });

        targetRevisionComboBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                DefaultListCellRenderer retValue = (DefaultListCellRenderer) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof XBCRev) {
                    retValue.setText("Revision " + ((XBCRev) value).getXBIndex());
                }

                return retValue;
            }
        });
    }

    public void setApplication(XBApplication application) {
        this.application = application;
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revisionSelectionPanel = new javax.swing.JPanel();
        targetRevisionComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        targetRevisionComboBox.setModel(revsModel);

        javax.swing.GroupLayout revisionSelectionPanelLayout = new javax.swing.GroupLayout(revisionSelectionPanel);
        revisionSelectionPanel.setLayout(revisionSelectionPanelLayout);
        revisionSelectionPanelLayout.setHorizontalGroup(
            revisionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisionSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(targetRevisionComboBox, 0, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        revisionSelectionPanelLayout.setVerticalGroup(
            revisionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revisionSelectionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(targetRevisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(revisionSelectionPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new CatalogSelectRevPanel(null, CatalogSpecItemType.NODE));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel revisionSelectionPanel;
    private javax.swing.JComboBox targetRevisionComboBox;
    // End of variables declaration//GEN-END:variables

    public boolean isSelectEnabled() {
        return selectEnabled;
    }

    public XBCItem getSpec() {
        return selectSpecPanel.getItem();
    }

    public void setSpec(XBCItem spec) {
        selectSpecPanel.setItem(spec);
    }

    public XBCRev getTarget() {
        return (XBCRev) targetRevisionComboBox.getSelectedItem();
    }

    public void setTarget(XBCRev rev) {
        XBCSpec specification;
        if (rev != null) {
            specification = rev.getParent();
            revsModel.setRevs(revService.getRevs((XBCSpec) specification));
            targetRevisionComboBox.setSelectedIndex(rev.getXBIndex().intValue());
        } else {
            specification = null;
        }

        setSpec(specification);
    }
}
