/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.bined.options.panel;

import java.util.List;
import java.util.ResourceBundle;
import org.exbin.framework.api.Preferences;
import org.exbin.framework.bined.preferences.BinaryAppearanceParameters;
import org.exbin.framework.gui.options.api.OptionsPanel;
import org.exbin.framework.gui.options.api.OptionsPanel.ModifiedOptionListener;
import org.exbin.framework.gui.utils.LanguageUtils;
import org.exbin.framework.gui.utils.WindowUtils;

/**
 * Hexadecimal appearance options panel.
 *
 * @version 0.2.1 2019/06/09
 * @author ExBin Project (http://exbin.org)
 */
public class BinaryAppearanceOptionsPanel extends javax.swing.JPanel implements OptionsPanel {

    private ModifiedOptionListener modifiedOptionListener;
    private final ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(BinaryAppearanceOptionsPanel.class);
    private final BinaryAppearanceOptionsPanelApi panelApi;

    public BinaryAppearanceOptionsPanel(BinaryAppearanceOptionsPanelApi panelApi) {
        this.panelApi = panelApi;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineWrapCheckBox = new javax.swing.JCheckBox();
        multiTabModeCheckBox = new javax.swing.JCheckBox();
        showValuesPanelCheckBox = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        lineWrapCheckBox.setSelected(true);
        lineWrapCheckBox.setText(resourceBundle.getString("lineWrapCheckBox.text")); // NOI18N
        lineWrapCheckBox.setName("lineWrapCheckBox"); // NOI18N

        multiTabModeCheckBox.setText(resourceBundle.getString("multiTabModeCheckBox.text")); // NOI18N
        multiTabModeCheckBox.setEnabled(false);
        multiTabModeCheckBox.setName("multiTabModeCheckBox"); // NOI18N

        showValuesPanelCheckBox.setSelected(true);
        showValuesPanelCheckBox.setText(resourceBundle.getString("showValuesPanelCheckBox.text")); // NOI18N
        showValuesPanelCheckBox.setName("showValuesPanelCheckBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineWrapCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(showValuesPanelCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(multiTabModeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineWrapCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showValuesPanelCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiTabModeCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new BinaryAppearanceOptionsPanel(null));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox lineWrapCheckBox;
    private javax.swing.JCheckBox multiTabModeCheckBox;
    private javax.swing.JCheckBox showValuesPanelCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<OptionsPanel.PathItem> getPath() {
        return null;
    }

    @Override
    public void loadFromPreferences(Preferences preferences) {
        BinaryAppearanceParameters binaryAppearanceParameters = new BinaryAppearanceParameters(preferences);
        lineWrapCheckBox.setSelected(binaryAppearanceParameters.isTextWordWrapping());
        showValuesPanelCheckBox.setSelected(binaryAppearanceParameters.showValuesPanel());
        multiTabModeCheckBox.setSelected(binaryAppearanceParameters.isMultiTabMode());
    }

    @Override
    public void saveToPreferences(Preferences preferences) {
        BinaryAppearanceParameters binaryAppearanceParameters = new BinaryAppearanceParameters(preferences);
        binaryAppearanceParameters.setTextWordWrapping(lineWrapCheckBox.isSelected());
        binaryAppearanceParameters.setShowValuesPanel(showValuesPanelCheckBox.isSelected());
        binaryAppearanceParameters.setMultiTabMode(multiTabModeCheckBox.isSelected());
    }

    @Override
    public void applyPreferencesChanges() {
        panelApi.setWordWrapMode(lineWrapCheckBox.isSelected());
        panelApi.setShowValuesPanel(showValuesPanelCheckBox.isSelected());
    }

    private void setModified(boolean modified) {
        if (modifiedOptionListener != null) {
            modifiedOptionListener.wasModified();
        }
    }

    @Override
    public void setModifiedOptionListener(ModifiedOptionListener listener) {
        modifiedOptionListener = listener;
    }
}
