/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.about.gui;

import java.util.List;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.table.DefaultTableModel;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.utils.LanguageUtils;
import org.exbin.framework.utils.WindowUtils;
import org.exbin.xbup.plugin.XBModuleRecord;

/**
 * List of modules panel.
 *
 * @version 0.2.1 2021/03/28
 * @author ExBin Project (http://exbin.org)
 */
@ParametersAreNonnullByDefault
public class AboutModulesPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(AboutModulesPanel.class);

    public AboutModulesPanel() {
        initComponents();
        init();
    }

    private void init() {
        // Fill list of modules
        modulesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    resourceBundle.getString("modulesTable.moduleNameColumn"), resourceBundle.getString("modulesTable.moduleDescriptionColumn"), resourceBundle.getString("modulesTable.moduleLicenseColumn")
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            @Nonnull
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
    }

    public void setApplication(XBApplication application) {
        DefaultTableModel modulesTableModel = (DefaultTableModel) modulesTable.getModel();
        List<XBModuleRecord> modulesList = application.getModuleRepository().getModulesList();
        for (XBModuleRecord moduleRecord : modulesList) {
            String moduleName;
            if (moduleRecord.getName().isEmpty()) {
                moduleName = moduleRecord.getModuleId();
            } else {
                moduleName = moduleRecord.getName();
            }
            String[] newRow = {moduleName, moduleRecord.getDescription()};
            modulesTableModel.addRow(newRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modulesScrollPane = new javax.swing.JScrollPane();
        modulesTable = new javax.swing.JTable();

        setEnabled(false);
        setLayout(new java.awt.BorderLayout());

        modulesScrollPane.setViewportView(modulesTable);

        add(modulesScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new AboutModulesPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane modulesScrollPane;
    private javax.swing.JTable modulesTable;
    // End of variables declaration//GEN-END:variables
}
