/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.about.gui;

import java.util.ResourceBundle;
import javax.annotation.ParametersAreNonnullByDefault;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.api.XBApplicationBundle;
import org.exbin.framework.utils.LanguageUtils;
import org.exbin.framework.utils.WindowUtils;

/**
 * List of authors panel.
 *
 * @version 0.2.1 2021/03/28
 * @author ExBin Project (http://exbin.org)
 */
@ParametersAreNonnullByDefault
public class AboutAuthorsPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(AboutAuthorsPanel.class);

    public AboutAuthorsPanel() {
        initComponents();
        init();
    }

    private void init() {
    }

    public void setApplication(XBApplication application) {
        ResourceBundle appBundle;
        if (application != null) {
            appBundle = application.getAppBundle();
        } else {
            appBundle = resourceBundle;
        }

        authorsTextArea.setText(appBundle.getString(XBApplicationBundle.APPLICATION_AUTHORS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorsScrollPane = new javax.swing.JScrollPane();
        authorsTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        authorsTextArea.setEditable(false);
        authorsScrollPane.setViewportView(authorsTextArea);

        add(authorsScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new AboutAuthorsPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane authorsScrollPane;
    private javax.swing.JTextArea authorsTextArea;
    // End of variables declaration//GEN-END:variables

}
