/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.editor.xbup.gui;

import java.awt.BorderLayout;
import java.util.ResourceBundle;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.gui.menu.api.MenuManagement;
import org.exbin.framework.gui.service.catalog.gui.CatalogEditorPanel;
import org.exbin.framework.gui.service.gui.CatalogAvailabilityPanel;
import org.exbin.framework.gui.service.gui.CatalogManagerPanelable;
import org.exbin.framework.gui.utils.LanguageUtils;
import org.exbin.framework.gui.utils.WindowUtils;
import org.exbin.xbup.core.catalog.XBACatalog;

/**
 * Panel for showing information about document block.
 *
 * @version 0.2.1 2019/06/29
 * @author ExBin Project (http://exbin.org)
 */
public class CatalogEditorWrapperPanel extends javax.swing.JPanel implements CatalogManagerPanelable {

    private XBApplication application;
    private final CatalogEditorPanel catalogEditorPanel;
    private final CatalogAvailabilityPanel catalogAvailabilityPanel;
    private XBACatalog catalog = null;
    private final ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(CatalogEditorWrapperPanel.class);

    public CatalogEditorWrapperPanel() {
        initComponents();
        catalogEditorPanel = new CatalogEditorPanel();
        catalogAvailabilityPanel = new CatalogAvailabilityPanel();
        init();
    }

    private void init() {
        add(catalogAvailabilityPanel, BorderLayout.CENTER);
    }

    public void setApplication(XBApplication application) {
        this.application = application;
        catalogEditorPanel.setApplication(application);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new CatalogEditorWrapperPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void setMenuManagement(MenuManagement menuManagement) {
        catalogEditorPanel.setMenuManagement(menuManagement);
    }

    @Override
    public void setCatalog(XBACatalog catalog) {
        if (this.catalog == null && catalog != null) {
            catalogAvailabilityPanel.setCatalog(catalog);
            catalogEditorPanel.setCatalog(catalog);
            removeAll();
            add(catalogEditorPanel, BorderLayout.CENTER);
            revalidate();
            repaint();
        } else if (this.catalog != null && catalog == null) {
            catalogAvailabilityPanel.setCatalog(catalog);
            removeAll();
            add(catalogAvailabilityPanel, BorderLayout.CENTER);
            revalidate();
            repaint();
            catalogEditorPanel.setCatalog(catalog);
        } else {
            catalogEditorPanel.setCatalog(catalog);
        }

        this.catalog = catalog;
    }
}
