onlineHelpAction.text=Online Help
onlineHelpAction.shortDescription=Show online help in default browser
onlineHelpAction.smallIcon=/org/exbin/jaguif/help/online/action/resources/icons/16px/help-contents-3.png
