/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.addon.manager.operation.gui;

import java.awt.BorderLayout;
import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JComponent;
import org.exbin.framework.App;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.framework.utils.WindowUtils;
import org.exbin.framework.utils.TestApplication;
import org.exbin.framework.utils.UtilsModule;

/**
 * Panel for addon installation / update operation.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class AddonOperationPanel extends javax.swing.JPanel {

    private final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AddonOperationPanel.class);
    private Controller controller;

    private final AddonOperationOverviewPanel overviewPanel = new AddonOperationOverviewPanel();
    private final AddonOperationLicensePanel licensePanel = new AddonOperationLicensePanel();
    private final AddonOperationDownloadPanel downloadPanel = new AddonOperationDownloadPanel();
    private final AddonOperationSuccessPanel successPanel = new AddonOperationSuccessPanel();
    
    private JComponent activePanel = null;

    public AddonOperationPanel() {
        initComponents();
        init();
    }

    private void init() {
        goToStep(Step.OVERVIEW);
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    public void goToStep(Step step) {
        if (activePanel != null) {
            remove(activePanel);
        }
        
        switch (step) {
            case OVERVIEW:
                activePanel = overviewPanel;
                break;
            case LICENSE:
                activePanel = licensePanel;
                break;
            case DOWNLOAD:
                activePanel = downloadPanel;
                break;
            case SUCCESS:
                activePanel = successPanel;
                break;
            default:
                throw new AssertionError();
        }
        
        add(activePanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }
    
    @Nullable
    public JComponent getActiveComponent() {
        return activePanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        TestApplication testApplication = UtilsModule.createTestApplication();
        testApplication.launch(() -> {
            testApplication.addModule(org.exbin.framework.language.api.LanguageModuleApi.MODULE_ID, new org.exbin.framework.language.api.utils.TestLanguageModule());
            WindowUtils.invokeWindow(new AddonOperationPanel());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public interface Controller {

    }
    
    public enum Step {
        OVERVIEW,
        LICENSE,
        DOWNLOAD,
        SUCCESS
    }
}
