defaultItem.icon=/org/exbin/jaguif/addon/manager/resources/icons/48px/puzzle.png
disabledState.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/dialog-cancel-2.png
disabledState.toolTip=Addon is disabled
updateAvailableState.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/software-update-available.png
updateAvailableState.toolTip=Update available
