defaultItem.icon=/org/exbin/jaguif/addon/manager/resources/icons/48px/puzzle.png
installVariant.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/update_misc.png
installVariant.toolTip=Install addon
updateVariant.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/software-update-available.png
updateVariant.toolTip=Update addon
removeVariant.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/edit-delete.png
removeVariant.toolTip=Remove addon
