dialog.title=Addon Manager
header.title=Addon Manager
header.description=Manage installed and available addons
header.icon=/org/exbin/jaguif/addon/manager/resources/icons/48px/plugin.png
closeButton.text=Close
cartButton.toolTipText=Show / hide cart for modifications operations
cartButton.icon=/org/exbin/jaguif/addon/manager/resources/icons/32px/basket.png
filterLabel.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/view-filter.png
searchLabel.icon=/org/exbin/jaguif/addon/manager/resources/icons/16px/edit-find-5.png
filterLabel.toolTipText=Filter
searchLabel.toolTipText=Search
cartButton.text=Cart
