newFileAction.text=New
newFileAction.shortDescription=Create new empty file
newFileAction.smallIcon=/org/exbin/jaguif/docking/resources/icons/16px/document-new.png
openFileAction.text=Open
openFileAction.shortDescription=Open a file
openFileAction.smallIcon=/org/exbin/jaguif/docking/resources/icons/16px/document-open.png
saveFileAction.text=Save
saveFileAction.shortDescription=Save the current file
saveFileAction.accelerator=ctrl pressed S
saveFileAction.smallIcon=/org/exbin/jaguif/docking/resources/icons/16px/document-save.png
saveAsFileAction.text=Save As
saveAsFileAction.shortDescription=Save file using new filename
saveAsFileAction.accelerator=shift ctrl pressed S
saveAsFileAction.smallIcon=/org/exbin/jaguif/docking/resources/icons/16px/document-save-as.png
fileCloseAction.text=Close
fileCloseAction.shortDescription=Close file
