/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.component.gui;

import java.awt.BorderLayout;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JComponent;

/**
 * Panel for multiple components organized by tabs.
 */
@ParametersAreNonnullByDefault
public class TabbedComponentsPanel extends javax.swing.JPanel {

    protected Controller controller;
    protected int activeIndex = -1;
    protected Page firstPage = null;

    public TabbedComponentsPanel() {
        initComponents();
        tabbedPane.addChangeListener((e) -> {
            int selectedIndex = tabbedPane.getSelectedIndex();
            changeActiveIndex(selectedIndex);
        });
    }

    public void addPage(Page page) {
        if (firstPage == null) {
            firstPage = page;
            add(page.getComponent(), BorderLayout.CENTER);
        } else {
            if (tabbedPane.getComponentCount() == 0) {
                remove(firstPage.getComponent());
                add(tabbedPane, BorderLayout.CENTER);
                tabbedPane.addTab(firstPage.getTitle(), firstPage.getComponent());
            }

            tabbedPane.addTab(page.getTitle(), page.getComponent());
        }
    }

    private void changeActiveIndex(int index) {
        if (activeIndex != index) {
            activeIndex = index;
            notifyActiveIndexChanged();
        }
    }

    private void notifyActiveIndexChanged() {
        if (controller != null) {
            controller.activeIndexChanged(activeIndex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        tabbedPane.setName("tabbedPane"); // NOI18N

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    public interface Controller {

        void activeIndexChanged(int index);
    }

    public interface Page {

        @Nonnull
        String getTitle();

        @Nonnull
        JComponent getComponent();
    }
}
