searchFindAction.text=Find
searchFindAction.shortDescription=Find words in text
searchFindAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find.png
searchFindNextAction.text=Find Again
searchFindNextAction.shortDescription=Repeat the last search
searchFindNextAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find.png
searchFindPreviousAction.text=Find Prev
searchFindPreviousAction.shortDescription=Repeat the last search in reverse order
searchFindPreviousAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find.png
searchReplaceAction.text=Replace
searchReplaceAction.shortDescription=Find and replace given string for another
searchReplaceAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find-replace.png
