/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.editor.xbup.panel;

import java.awt.BorderLayout;
import java.util.ResourceBundle;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.gui.menu.api.MenuManagement;
import org.exbin.framework.gui.service.catalog.panel.CatalogEditorPanel;
import org.exbin.framework.gui.service.panel.CatalogAvailabilityPanel;
import org.exbin.framework.gui.service.panel.CatalogManagerPanelable;
import org.exbin.framework.gui.utils.LanguageUtils;
import org.exbin.framework.gui.utils.WindowUtils;
import org.exbin.xbup.core.catalog.XBACatalog;

/**
 * Panel for showing information about document block.
 *
 * @version 0.2.1 2019/06/28
 * @author ExBin Project (http://exbin.org)
 */
public class CatalogEditorWrapperPanel extends javax.swing.JPanel implements CatalogManagerPanelable {

    private XBApplication application;
    private final CatalogEditorPanel catalogEditorPanel;
    private final CatalogAvailabilityPanel catalogAvailabilityPanel;
    private XBACatalog catalog = null;
    private final ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(CatalogEditorWrapperPanel.class);

    public CatalogEditorWrapperPanel() {
        initComponents();
        catalogEditorPanel = new CatalogEditorPanel();
        catalogAvailabilityPanel = new CatalogAvailabilityPanel();
        add(catalogAvailabilityPanel, BorderLayout.CENTER);
    }

    public void setApplication(XBApplication application) {
        this.application = application;
        catalogEditorPanel.setApplication(application);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WindowUtils.invokeDialog(new CatalogEditorWrapperPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void setMenuManagement(MenuManagement menuManagement) {
        catalogEditorPanel.setMenuManagement(menuManagement);
    }

    @Override
    public void setCatalog(XBACatalog catalog) {
        if (this.catalog == null && catalog != null) {
            catalogAvailabilityPanel.setCatalog(catalog);
            catalogEditorPanel.setCatalog(catalog);
            removeAll();
            add(catalogEditorPanel, BorderLayout.CENTER);
            revalidate();
            repaint();
        } else if (this.catalog != null && catalog == null) {
            catalogAvailabilityPanel.setCatalog(catalog);
            removeAll();
            add(catalogAvailabilityPanel, BorderLayout.CENTER);
            revalidate();
            repaint();
            catalogEditorPanel.setCatalog(catalog);
        } else {
            catalogEditorPanel.setCatalog(catalog);
        }

        this.catalog = catalog;
    }
}
