/*
 * Copyright (C) ExBin Project
 *
 * This application or library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * This application or library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along this application.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.exbin.framework.editor.xbup.panel;

import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JComponent;

/**
 * Document viewer panel.
 *
 * @version 0.2.1 2020/03/13
 * @author ExBin Project (http://exbin.org)
 */
@ParametersAreNonnullByDefault
public class DocumentViewerPanel extends javax.swing.JPanel {

    private final List<ViewRecord> viewRecords = new ArrayList<>();
    private int activeView = 0;

    public DocumentViewerPanel() {
        initComponents();
        init();
    }

    private void init() {
        modeComboBox.addItemListener((ItemEvent e) -> {
            int selectedIndex = modeComboBox.getSelectedIndex();
            if (selectedIndex >= 0) {
                ViewRecord prevRecord = viewRecords.get(activeView);
                remove(prevRecord.component);
                ViewRecord record = viewRecords.get(selectedIndex);
                add(record.component, BorderLayout.CENTER);
                activeView = selectedIndex;
            }
        });
    }

    public void addView(String name, JComponent component) {
        if (viewRecords.isEmpty()) {
            add(component, BorderLayout.CENTER);
        }

        viewRecords.add(new ViewRecord(name, component));
        modeComboBox.addItem(name);
    }

    public void removeAllViews() {
        if (!viewRecords.isEmpty()) {
            ViewRecord prevRecord = viewRecords.get(activeView);
            remove(prevRecord.component);
            modeComboBox.removeAllItems();
            viewRecords.clear();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());
        add(modeComboBox, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> modeComboBox;
    // End of variables declaration//GEN-END:variables

    private static final class ViewRecord {

        public ViewRecord(String name, JComponent component) {
            this.name = name;
            this.component = component;
        }

        String name;
        JComponent component;
    }
}
